version: "3.8"

services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - ecommerce-analyzer-db:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - analyzer-dev-network
    env_file:
      - ecommerce_analyzer/env/dev.env
    ports:
      - 5433:5432

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
      network: analyzer-dev-network
      args:
        - DEV_MODE=true
    restart: always
    depends_on:
      - db
    networks:
      - analyzer-dev-network
    env_file:
      - ecommerce_analyzer/env/dev.env
    ports:
      - 8000:80

volumes:
  ecommerce-analyzer-db:

networks:
  analyzer-dev-network:
    external: true
